/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Idempotency": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Listings": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MockMarketplace": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "PublishDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PublishQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "WebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}